modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/MinerArcana/Floralchemy/issues"

[[mods]]
    modId="floralchemy"
    version="${file.jarVersion}"
    displayName="Floralchemy"
    credits="BrassGoggledCoders Artists"
    authors="SkySom, FreneticScribbler, DivineAspect"
    description='''
        Flower Power!
    '''

[[dependencies.floralchemy]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"
